# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version  of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-13

version: '2'

services:
    # microservice for ...
    cfsd18-sim-globalposition:
        image: chalmersrevere/opendlv-sim-global-amd64:v0.0.5
        network_mode: "host"
        command: "/usr/bin/opendlv-sim-global --cid=${CID} --freq=50 \
        --frame-id=232 --x=${X} --y=${Y} --yaw=${YAW}"

    # microservice for ...
    cfsd18-sim-cognition-detectcone:
        image: detectcone:pre
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/usr/bin/cfsd18-sim-cognition-detectcone --cid=${CID} --verbose=0 --id=231 --freq=10 \
        --detectRange=10 --detectWidth=5 --fakeSlamActivated=${FAKESLAM} --nConesFakeSlam=10 --startX=${X} --startY=${Y} --startHeading=${YAW} \
        --mapFilename=${MAP}"

    # microservice for ...
    cfsd18-cognition-detectconelane:
        image: detectconelane:dev
        network_mode: "host"
        command: "/usr/bin/cfsd18-cognition-detectconelane --cid=${CID} --verbose=0 --id=211 --detectConeId=118 --slamId=120 --simDetectConeId=231 --attentionId=116 \
        --gatheringTimeMs=50 --separationTimeMs=10 \
        --alwaysSlam=${FAKESLAM} --guessDistance=3 --minGuessSeparation=1.5 --latePerpGuessing=0 --maxConeAngle=1.570796325 --behindMemoryDistance=2.0 \
        --maxConeWidthSeparation=3.0 --widthSeparationMargin=1.0 \
        --maxConeLengthSeparation=5.0 --lengthSeparationMargin=1.0 \
        --nLapsToGo=1 --lapCounterLockTime=10 --useNewConeLapCounter=1 --nMinOrangeFrames=2 --nMinDisappearanceFrames=2 \
        --useAccelerationMode=0 --useSkidpadMode=0"

    # microservice for ...
    cfsd18-cognition-track:
        image: track:steering
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/usr/bin/cfsd18-cognition-track --cid=${CID} --verbose=0 --id=221 --surfaceId=211 --speedId=232 --slamId=120 \
        --gatheringTimeMs=500 --separationTimeMs=100 \
        --wheelAngleLimit=25 --wheelBase=${WB} --frontToCog=${FTC} \
        --distanceBetweenPoints=1.0 --useTraceBack=0 --curvEstStepsize=5 \
        --useMoveOrigin=1 --useCurveFitPath=1 --polynomialDegree=3 --previewTime=0.3 --minPrevDist=3 --steerRate=30 --curveLimitedSteerRate=30 --ignoreOnePointPaths=1 --calcDtaOnX=1 \
        --previewTimeSlam=0.3 --minPrevDistSlam=1 --steerRateSlam=50 \
        --startAimVel=0.5 --accFreq=1 --axSpeedProfile=8 --useAyReading=0 --velocityLimit=10 --mu=${MU} --axLimitPositive=5 --axLimitNegative=-5 --headingErrorDependency=0.7f --curveDetectionAngle=0.3f --curveExitAngleLim=0.1f; --curveDetectionAngleSlam=1.0f --curveDetectionPoints=20 \
        --aKp=1 --aKd=0 --aKi=0 --bKp=2 --bKd=0 --bKi=0.2 --sKp=1 --sKd=0 --sKi=0.5 --keepConstVel=5 --diffToBrakeVel=0 --critDiff=0.5 --critDiff2=0.1 \
        --useSharp=0 --nSharpPreviewPoints=10 --sharpK1=0.17 --sharpKy=0.5 --sharpBigC=0.17 --sharpSmallC=1 \
        --usePolyFit=0 --pointsPerPolySegment=10 --segmentizePolyfit=0"


    cfsd18-sim-cognition-vehiclemodel:
        image: vehiclemodel:vx
        network_mode: "host"
        command: "/usr/bin/cfsd18-sim-cognition-vehiclemodel --cid=${CID} --verbose=0 --id=232 --freq=50 \
        --frontToCog=${FTC} --rollRes=0.02 --mass=188 --momentOfInertiaZ=105 --length=${WB} --frictionCoefficient=${MU} \
        --magicFormulaCAlpha=25229 --magicFormulaC=1 --magicFormulaE=-2"

    cfsd18-sim-visualization:
        image: visualization:FSGb
        network_mode: "host"
        command: "--cid=${CID}"
